### ISSUE TITLE
Re-generate trajectories for all compounds - implicit solvent, explicit solvent, and vacuum

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/FreeSolv#15]
I've had some requests for trajectory files associated with the calculated hydration free energies - especially, for endpoint trajectories. I would like to see all of these re-generated via a consistent, reproducible protocol from the latest version of input files.

This could be part of an effort to re-calculate all of the hydration free energies with a consistent protocol (which has been discussed elsewhere) or simply a re-generation of endpoint trajectories separately from that. 

Relatedly, there is also some interest in having calculated hydration free energies in implicit solvent, along with associated endpoint trajectories. 

Thoughts?

**Comment by jchodera** [comment]
I think we should break this a few three separate issues to make it easy to tackle these one at a time:

## Trajectories
* Generate explicit solvent trajectories for all compounds
* Generate implicit solvent trajectories for all compounds
* Generate vacuum trajectories for all compounds

## Hydration free energies
* Compute explicit solvent hydration free energies for all compounds
* Compute implicit solvent hydration free energies for all compounds

## Related questions:
* What format should the trajectories be made available in?
* Is it OK if all of these are generated via OpenMM?
* I presume we should use the same GAFF/AM1-BCC files, including the same exact charges; we presumably want to use the new consistent mol2 files I generate with a single script from PR #11, right?

**Comment by davidlmobley** [comment]
Agreed, I'll do that. Though, there is some coupling - i.e. if we were
doing all of the hydration free energies, it would be trivial to generate
the trajectories. If we are doing the trajectories it is not necessarily
trivial to do the hydration free energies.

DM


On Tue, Feb 17, 2015 at 1:35 AM, John Chodera <notifications@github.com>
wrote:

> I think we should break this a few three separate issues to make it easy
> to tackle these one at a time:
> Trajectories
>
>    - Generate explicit solvent trajectories for all compounds
>    - Generate implicit solvent trajectories for all compounds
>    - Generate vacuum trajectories for all compounds
>
> Hydration free energies
>
>    - Compute explicit solvent hydration free energies for all compounds
>    - Compute implicit solvent hydration free energies for all compounds
>
> Related questions:
>
>    - What format should the trajectories be made available in?
>    - Is it OK if all of these are generated via OpenMM?
>    - I presume we should use the same GAFF/AM1-BCC files, including the
>    same exact charges; we presumably want to use the new consistent mol2 files
>    I generate with a single script from PR #11
>    <https://github.com/choderalab/FreeSolv/pull/11>, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/choderalab/FreeSolv/issues/15#issuecomment-74640205>.
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by davidlmobley** [comment]
OK, so the current plan on this issue is:

*Generate explicit solvent trajectories for all compounds
*Generate implicit solvent trajectories for all compounds
*Generate vacuum trajectories for all compounds
