### ISSUE TITLE
Migrate issues and close this repo?

### ISSUE THREAD

**Issue by davidlmobley** [MobleyLab/FreeSolv#25]
@jchodera - do you have any objection to closing this repo, or at least updating the README.md to reflect that the official repo is elsewhere, if I migrate the issues over to github.com/mobleylab/freesolv? 

Now that my group is up on GitHub, it would probably be best for me to continue to maintain this on our site rather than yours, especially since we have some updates coming soon.

**Comment by jchodera** [comment]
The official repo is elsewhere?

**Comment by jchodera** [comment]
Wait, when and how did this happen? What *is* the official repo?

**Comment by jchodera** [comment]
Ah, I see, you have a fork in `mobleylab`.

How about this:
* You delete your fork
* I transfer the repository to `mobleylab` so that you own the main repo
* We enable [zenodo](https://guides.github.com/activities/citable-code/) integration so we automatically assign a DOI to each release, and add a zenodo badge to the `README.md`
* We update the `README.md` with the list of contributors from my lab who helped with the cleanup here so we don't accidentally leave anyone off future publications, and so they get credit
* We cut a new release

**Comment by davidlmobley** [comment]
@jchodera - sounds great. I'll delete my fork now. Thanks.

**Comment by davidlmobley** [comment]
Also, I definitely need to know who was involved with any sort of extensive cleanup (I didn't recall that anyone had done anything substantial other than put it onto GitHub, but that's why it's important to have a record) as we're going to have a new paper soon so we'll need them for the authors list.

**Comment by davidlmobley** [comment]
OK, my fork is now deleted, @jchodera . Thanks.

**Comment by jchodera** [comment]
Looks like I need temporary admin rights to `mobleylab`:

> You don’t have admin rights to MobleyLab

**Comment by davidlmobley** [comment]
I just sent an invite to the requisite team, @jchodera .

**Comment by jchodera** [comment]
Transferred!

Can you handle the other steps?
- [ ] Enable zenodo integration so we automatically assign a DOI to each release, and add a zenodo badge to the README.md
- [ ] Update the README.md with the list of contributors from my lab who helped with the cleanup here so we don't accidentally leave anyone off future publications, and so they get credit. You can use the git commit history to check.
- [ ] Cut a new minor release, which will trigger a zenodo DOI assignment

**Comment by davidlmobley** [comment]
Mostly, yes, @jchodera - except that I need to know if there is anyone from your lab who did anything NOT recorded in the pull requests. The pull requests basically just show three things:

* Lee-Ping added a column to a text file by pulling it from a pickle file
* Kyle removed some extra files left behind by Antechamber
* You added a script to charge molecules via Bayly's recommended procedure

All of the other issues I'm seeing on there were initiated and resolved by me. But maybe I'm missing other important contributions from your group??

Unless I'm missing additional contributions, this probably means you would get included on a publication and the other two would likely get acknowledgments...?
