### ISSUE TITLE
rebuild_freesolv.py script

### ISSUE THREAD

**Issue by kadiliissaar** [MobleyLab/FreeSolv#46]
Hello!

I have been trying to run the rebuild_freesolv.py script but it seems the molecules do not get  correct coordinates, in fact they get generated with the coordinates of all atoms as zeros (as opposed to the files that are already available in the mol2files_sybyl folder). Do you know what the reason for this may be?

Best wishes,
Kadi

**Comment by jchodera** [comment]
It looks like the `scripts/rebuild_freesolv.py` script relies on `openmoltools`, which is pretty fragile and hasn't always remained backwards-compatible:
https://github.com/choderalab/openmoltools
![image](https://user-images.githubusercontent.com/3656088/81869939-c46e9280-9529-11ea-9d3e-8f4b12c322bf.png)
We've been hoping to replace all this functionality with more modern tools in the openforcefield toolkit and OpenMM, but haven't yet updated the FreeSolv repo yet.
 
It looks like the default behavior of [`get_charges()`](https://github.com/choderalab/openmoltools/blob/master/openmoltools/openeye.py#L13) changed at some point to no longer retain the conformers generated during the charging process. 

You should be able to just change [this line](https://github.com/MobleyLab/FreeSolv/blob/master/scripts/rebuild_freesolv.py#L48) from
```python
    charged = openmoltools.openeye.get_charges(molecule)
```
to
```python
    charged = openmoltools.openeye.get_charges(molecule, keep_confs=1)
```
and you'll have a conformer!

**Comment by kadiliissaar** [comment]
Yes, this solves the problem - thanks a lot!
